spring.application.name=taskmanagement

spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=SYSTEM
spring.datasource.password=2512
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

#auto creation of DB
spring.jpa.hibernate.ddl-auto=update

# JPA logging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


#addition logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE